data:
  train_path: 'data/train_data.csv'
  predict_path: 'data/predict_data.csv'
  target_col: "depression"
  columns:
    - 'id'
    - 'name'
    - 'gender'
    - 'age'
    - 'city'
    - 'occupation_status'
    - 'profession'
    - 'academic_pressure'
    - 'work_pressure'
    - 'cgpa'
    - 'study_satisfaction'
    - 'job_satisfaction'
    - 'sleep_duration'
    - 'dietary_habits'
    - 'degree'
    - 'suicidal_thoughts'
    - 'work_study_hours'
    - 'financial_stress'
    - 'family_history_mental_illness'
    - 'depression'
  features:
    cat_binary_features:
      - "gender"
      - "occupation_status"
      - "suicidal_thoughts"
      - "family_history_mental_illness"
    cat_multiclass_features:
      - "dietary_habits"
      - "sleep_duration"
      - "degree"
    cat_highcard_features:
      - "profession"
      - "city"
    num_standard_features:
      - "age"
      - "work_study_hours"
      - "financial_stress"
      - "work_academic_stress"
      - "job_study_satisfaction"
    num_custom_features:
      - "academic_pressure"
      - "work_pressure"
      - "cgpa"
      - "study_satisfaction"
      - "job_satisfaction"

data_split:
  test_size: 0.1
  random_state: 42

preprocessing:
  encoder_drop_lr: "first"
  encoder_drop_rf: null

feature_selection:
  estimator: "random_forest"
  estimator_params:
      class_weight: 'balanced'
      n_estimators: 100
      random_state: 42
  params:
    threshold: 0.01
  params_grid:
    feature_selector__threshold: [0.001, 0.01, 0.1]

models:
  logistic_regression:
    name: "logistic_regression"
    params:
      class_weight: "balanced"
      random_state: 42
      solver: "saga"
      max_iter: 2000
    params_grid:
      standard_preprocessor__categorical__cat_multiclass__encoder__drop: ["first"]
      model__C: [0.1, 1, 10]
      model__penalty: ["l1", "l2"]
    output_path: "models/model_lr.pkl"
  random_forest:
    name: "random_forest"
    params:
      class_weight: "balanced"
      random_state: 42
    params_grid:
      standard_preprocessor__categorical__cat_multiclass__encoder__drop:  [null]
      model__n_estimators: [50, 100, 150]
      model__max_depth: [null, 10, 20]
      model__min_samples_leaf: [4, 6]
      bootstrap: [True, False]
    output_path: "models/model_rf.pkl"

cross_validation:
  n_splits: 5
  shuffle: true
  random_state: 42